import { Link } from 'react-router-dom'
import { Sparkles, Scale, Heart, ArrowLeft } from 'lucide-react'

export default function About() {
  return (
    <div className="min-h-screen pt-14">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-20">
        
        <Link to="/" className="btn-ghost text-[13px] mb-8 inline-flex">
          <ArrowLeft size={14} /> Back
        </Link>

        <p className="label mb-4">About Pandorax</p>
        <h1 className="font-serif font-medium text-[36px] sm:text-[48px] leading-[1.1] tracking-tight mb-8">
          The internet used to be for <em className="text-accent-gold italic">discovery</em>. We want that back.
        </h1>

        <div className="prose prose-sm sm:prose-base max-w-none text-ink-muted leading-relaxed mb-16" style={{ fontSize: '16px' }}>
          <p className="mb-6">
            Most of the modern internet is built on a very specific business model: harvesting your attention and selling it to advertisers. To do this, algorithms are tuned to provoke outrage, anxiety, and mindless scrolling.
          </p>
          <p className="mb-6">
            <strong>Pandorax is an escape hatch.</strong>
          </p>
          <p>
            We are a registered non-profit dedicated entirely to the cultivation of human curiosity. We don't care about "time on site." We don't have shareholders demanding infinite growth. We just want to remind you that the universe is strange, beautiful, and deeply fascinating.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 sm:gap-12 py-12 border-y border-ink/10">
          <div className="flex flex-col gap-3">
            <Scale className="text-accent-gold" size={24} />
            <h3 className="font-serif font-medium text-[18px] text-ink">100% Non-Profit</h3>
            <p className="text-[14px] text-ink-muted leading-relaxed">
              No ads, no paywalls, no corporate sponsors dictating our content. We are funded entirely by grants and voluntary donations from our community.
            </p>
          </div>
          <div className="flex flex-col gap-3">
            <Heart className="text-accent-coral" size={24} />
            <h3 className="font-serif font-medium text-[18px] text-ink">Curated, not Calculated</h3>
            <p className="text-[14px] text-ink-muted leading-relaxed">
              Our feed isn't generated by an engagement algorithm. Every Wonder and Simulation is hand-picked by human science communicators and researchers.
            </p>
          </div>
          <div className="flex flex-col gap-3">
            <Sparkles className="text-accent-indigo" size={24} />
            <h3 className="font-serif font-medium text-[18px] text-ink">Open Source</h3>
            <p className="text-[14px] text-ink-muted leading-relaxed">
              Our code, our data structures, and our simulations are open source. We believe knowledge infrastructure should belong to everyone.
            </p>
          </div>
        </div>

        <div className="mt-16 text-center">
          <h3 className="font-serif font-medium text-[24px] mb-4">Feed your mind.</h3>
          <Link to="/feed" className="btn-primary justify-center">
            Start Exploring →
          </Link>
        </div>

      </div>
    </div>
  )
}